
[build]
  publish = "."
  command = "echo 'No build command needed - static site'"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=(), ambient-light-sensor=(), autoplay=(), encrypted-media=(), fullscreen=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), web-share=(), xr-spatial-tracking=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Origin-Agent-Cluster = "?1"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://www.googletagmanager.com https://connect.facebook.net https://cdn.jsdelivr.net/npm/gsap@3.12.2/dist/gsap.min.js https://cdn.jsdelivr.net/npm/tsparticles@2.12.0/tsparticles.bundle.min.js https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.js https://cdn.jsdelivr.net/npm/tone@14.7.77/build/Tone.js https://cdn.jsdelivr.net/npm/date-fns@2.30.0/index.min.js blob: wss://api.operatoruplift.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://images.pexels.com https://placehold.co blob:; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://fcm.googleapis.com https://www.googletagmanager.com https://connect.facebook.net https://api.ipify.org https://api.operatoruplift.com wss://api.operatoruplift.com; frame-src 'self' https://www.facebook.com; worker-src 'self' blob:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'self'; upgrade-insecure-requests; require-trusted-types-for 'script'; trusted-types 'default'"

# Cache Control for Static Assets
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML files - no cache for dynamic content
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Manifest and Service Worker - no cache
[[headers]]
  for = "manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects
[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/press"
  to = "/press-release.html"
  status = 200

[[redirects]]
  from = "/mvp"
  to = "/MVP Launch Page.html"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions
[functions]
  directory = "netlify/functions"

# Environment Variables (set these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  FIREBASE_API_KEY = "AIzaSyCUVSEKUKC_suEIVuguflAus1zM7b0E3NY"
  FIREBASE_AUTH_DOMAIN = "operatoruplift-12b92.firebaseapp.com"
  FIREBASE_PROJECT_ID = "operatoruplift-12b92"
  FIREBASE_STORAGE_BUCKET = "operatoruplift-12b92.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "414885610296"
  FIREBASE_APP_ID = "1:414885610296:web:5195fb67878457ddd137cd"
  FIREBASE_MEASUREMENT_ID = "G-JT3N5NX378"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"

# Build Hooks (optional)
# [build.hooks]
#   pre_build = "npm run prebuild"
#   post_build = "npm run postbuild"

# Edge Functions (optional)
# [[edge_functions]]
#   function = "edge-function"
#   path = "/api/*"
