[build]
  publish = "build"
  functions = "netlify/functions"
  command = "npm run build:netlify"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.tailwindcss.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://images.pexels.com https://placehold.co https://pbs.twimg.com; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://fcm.googleapis.com https://www.googletagmanager.com https://connect.facebook.net https://api.ipify.org https://api.operatoruplift.com wss://api.operatoruplift.com https://fonts.googleapis.com https://cdn.tailwindcss.com https://cdn.jsdelivr.net; frame-src 'self'"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Function-specific headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  ALLOWED_ORIGIN = "https://your-production-domain.netlify.app"

# Environment variables for development
[context.deploy-preview.environment]
  NODE_ENV = "development"
  ALLOWED_ORIGIN = "https://your-preview-domain.netlify.app"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "development"
  ALLOWED_ORIGIN = "https://your-branch-domain.netlify.app" 

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
