[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Build completed'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  headers = {X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.gstatic.com https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://www.googletagmanager.com https://connect.facebook.net blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://images.pexels.com https://placehold.co; connect-src 'self' https://firestore.googleapis.com https://identitytoolkit.googleapis.com https://fcm.googleapis.com https://www.googletagmanager.com https://connect.facebook.net https://api.ipify.org; frame-src 'self' https://www.facebook.com; worker-src 'self' blob:"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Function-specific headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Environment variables for production
[context.production.environment]
  NODE_ENV = "production"
  ALLOWED_ORIGIN = "https://your-production-domain.netlify.app"

# Environment variables for development
[context.deploy-preview.environment]
  NODE_ENV = "development"
  ALLOWED_ORIGIN = "https://your-preview-domain.netlify.app"

# Environment variables for branch deployments
[context.branch-deploy.environment]
  NODE_ENV = "development"
  ALLOWED_ORIGIN = "https://your-branch-domain.netlify.app" 

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
